CREATE TABLE pratos (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(20) NOT NULL,
	descricao VARCHAR(100) NOT NULL,
	preco DECIMAL(10,2) NOT NULL,
	id_restaurante BIGINT(20) NOT NULL,
	FOREIGN KEY(id_restaurante) REFERENCES restaurantes(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;